### ISSUE TITLE
Add new C# MVC website

### ISSUE THREAD

**Issue by jayhilden** [tommygithub/MVCPlayground#3]
Create a new C# MVC website project.  When the website loads have it solve the classic ```fizbuzz``` problem and prints the results to the screen.

```
    /// <summary>
    /// For the numbers zero through 1000, use the following requirements:
    /// 1. If i is a multiple of 3 return "Fizz"
    /// 2. If i is a multiple of 5 return "Buzz"
    /// 3. If i is a multiple of 15 return "FizzBuzz"
    /// 4. Otherwise, return the number
    /// </summary>
```

**Comment by jayhilden** [comment]
@tommygithub I just downloaded the code and launched the website, it didn't run the FizzBuzz stuff.  Have you done that piece yet?

**Comment by tommygithub** [comment]
I haven't. I was hoping you could point me in the right direction on where
to write that code. I've been doing some MVC tutorial stuff online, but it
hasn't seemed to help much there. Currently doing the gitignore file.

**Comment by jayhilden** [comment]
@tommygithub 

We're going to need a few things:
1. A Controller for FizzBuzz
2. A FizzBuzz service
3. A View to display the results that uses a strongly typed view model

I should then be able to go to ```/FizzBuzz``` and view the results

Think of controllers as traffic cops, they direct the user to the correct thing that does the work.  The service is the thing that does the work.

**Comment by tommygithub** [comment]
Okay good stuff. I did a pull request for the .gitignore file, but I'm not
100% sure if I ignored the files correctly.

**Comment by jayhilden** [comment]
Tom, what's the word on this issue?  I still haven't seen anything where you solved this fizzbuzz problem.
